### ISSUE TITLE
Request for Visit 2.7.0 'windowsBuild' Folder

### ISSUE THREAD

**Issue by Bigstart** [visit-dav/visit-deps#164]

**Comment by biagas** [comment]
Those files are no longer available. The installer executable for 2.7 is still available on our page hosting older [Executables.](
https://sd.llnl.gov/simulation/computer-codes/visit/executables)

**Comment by Bigstart** [comment]
> Those files are no longer available. The installer executable for 2.7 is still available on our page hosting older [Executables.](https://sd.llnl.gov/simulation/computer-codes/visit/executables)

Thank you very much for your response. If I want to run version 2.7 of Visit, do I need to compile the third-party libraries as 64-bit libraries myself? Additionally, when compiling version 2.7 of Visit, should I specify it as 64-bit?   or  Both the libraries and version 2.7 of Visit should be 32-bit.?

**Comment by biagas** [comment]
If you use the installer, you choose whether you want 32 bit or 64 bit. Just download the correct version. The compiled thirdparty dlls are included, nothing else is needed to run VisIt.  Just install VisIt.

**Comment by Bigstart** [comment]
> If you use the installer, you choose whether you want 32 bit or 64 bit. Just download the correct version. The compiled thirdparty dlls are included, nothing else is needed to run VisIt. Just install VisIt.

Thank you very much, I have successfully compiled.
